#!/bin/bash

set -e

# stop service, if running 

PIDFILES_DIR=/var/run/cstbox
SVC="cstbox-modbus"

if [ -f $PIDFILES_DIR/$SVC.pid ] ; then
    service $SVC stop
fi

# unregister service from init process

#echo "Removing any system startup links for $svc..."
#update-rc.d -f $SVC remove > /dev/null
